#include <gtest/gtest.h>
#include <string>

#include "atg-math/information.h"


TEST(VersionTest, VersionString) {
    // The version string is generated by the VERSION property on the
    // project() directive in the main CMakeLists.txt. If this test ever
    // fails verify the VERSION property matches this expected string
    // before debugging.
    const std::string expected{"1.0.0"};
    ASSERT_EQ(expected, atg_math::getVersion());
}
